name: build-to-codeDeploy
#
run-name: ${{ github.actor }} is deploying ${{ github.event.repository.name }}

on:
  push:
    branches:
      - main

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_id
jobs:
    setup:
        name: Set-up
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: latest
            - name: Clone repo
              uses: actions/checkout@v3
            - name: Install packages
              run: npm i
              # https://stackoverflow.com/a/63350136/18686901
            - name: 'Create env file'
              run: |
                echo "${{ secrets.ENV_FILE }}" > .env
            - name: 'Build project'
              run: npm run build
            - name: 'Check files'
              run: ls -la
            - name: ssh deploy
              uses: easingthemes/ssh-deploy@v4.1.8
              # `SSH_PRIVATE_KEY`, `REMOTE_HOST`, `REMOTE_USER`
              with:
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                REMOTE_HOST: ${{ secrets.HOST_DNS }}
                REMOTE_USER: ${{ secrets.USERNAME }}
                # SOURCE: |
                #   build/
                #   package.json
                #   .env
                TARGET: /home/${{ secrets.USERNAME }}/DisCal/build
                SCRIPT_AFTER: |
                            ls -la

              
              