name: build-to-codeDeploy
#
run-name: ${{ github.actor }} is deploying ${{ github.event.repository.name }}

on:
  push:
    branches:
      - main

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_id
jobs:
    setup:
        name: Set-up
        runs-on: ubuntu-latest
        steps:
            # - name: Use Node.js
            #   uses: actions/setup-node@v3
            #   with:
            #     node-version: latest
            # - name: Clone repo
            #   uses: actions/checkout@v3
            # - name: Install packages
            #   run: npm i
            # - name: 'Create env file'
            #   run: |
            #     echo "${{ secrets.ENV_FILE }}" > .env
            - name: 'test credentials.json'
              run: |
                echo "${{ vars.CREDENTIALS }}"'
            # - name: Deploy commands
            #   run: npm run deploy-commands
            # - name: Build project
            #   run: npm run build
            # - name: Checking files
            #   run: ls -a
  

    # build:
    #     needs: setup
    #     name: build
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checking files
    #           run: ls

